### ISSUE TITLE
On focus the Radio / Checkbox buttons on Firefox show a blue focus indicator behind the styled focus.

### ISSUE THREAD

**Issue by alan-cole** [dpc-sdp/ripple-framework#1090]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.2
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.15.5
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Go to https://www.ripple.sdp.vic.gov.au/storybook/?path=/story/forms-radio-group--default-variant on Firefox, use TAB and arrows to move through the radio button.

### Describe the bug

Blue focus indicator shows on Firefox that does not show on Chrome.

https://github.com/dpc-sdp/ripple-framework/assets/12739575/89fc1cf8-570d-47aa-885f-52dbcec57023

### Final checks

- [X] Read the [contribution guide](https://ripple.sdp.vic.gov.au/design-system/about/contributing).
- [X] Check existing [discussions](https://github.com/dpc-sdp/ripple-framework/discussions) and [issues](https://github.com/dpc-sdp/ripple-framework/issues).

**Comment by dylankelly** [comment]
closed in #1091
