### ISSUE TITLE
Align Primary Nav, Nav Bar Action items vertically

### ISSUE THREAD

**Issue by eschweitzer78** [dpc-sdp/ripple-framework#1112]
### Describe the feature

Align nav bar action items vertically in a primary nav.

Check current state ->
[Public Storybook for Primary Nav](https://www.ripple.sdp.vic.gov.au/storybook/iframe?id=core-navigation-primary-nav--default-story&args=&viewMode=story&globals=theme:undefined;buttonTheme:default)

### Motivation

Aligned items are more aesthetically pleasing IMHO.

### Proposal

Thanks for all the great work you do!

Nav Bar action items that are of toggle type are not perfectly aligned with those of link type (off by 1px both on Chrome and Safari):

![image](https://github.com/dpc-sdp/ripple-framework/assets/20468027/573342d2-64ee-476a-a7d5-92192487219e)

Adjusting the display of .rpl-primary-nav__nav-bar-action>div to flex seems to solve it (and places the chevron on the right hand side of the two-line action):

![image](https://github.com/dpc-sdp/ripple-framework/assets/20468027/1cbf3f54-9cfa-4259-a5c0-7957da982098)

Perhaps this is an adjustment you could consider?

Misaligned chevron down icons are not eye-pleasing either - I'd prefer everything aligned on a baseline, but that would be a more substantial change...

### Benefits

Alignment is aesthetically pleasing.

### Drawbacks

Introduces a change in appearance. 

### Adoption strategy

No adoption strategy required.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be created outside of Ripple-framework as a layer?

### Final checks

- [X] I have read the [contribution guide](https://ripple.sdp.vic.gov.au/design-system/about/contributing) for information on submitting a feature request.
- [X] I have checked the [discussions](https://github.com/dpc-sdp/ripple-framework/discussions) and [issues](https://github.com/dpc-sdp/ripple-framework/issues) for duplicate feature requests.

**Comment by lambry** [comment]
Closing issue as this has been address here: https://github.com/dpc-sdp/ripple-framework/pull/1204
