### ISSUE TITLE
[BUG] Can not redirect when the URL has trailing slash

### ISSUE THREAD

**Issue by awset** [dpc-sdp/ripple-framework#1178]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.20.2
- Nuxt Version:     3.6.5
- Nitro Version:    2.9.4
- Package Manager:  npm@10.5.0
- Builder:          vite
- User Config:      css, runtimeConfig, extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction
I use ESV site for testing.

Go to below URLs to test.
http://localhost:3000/about-esv/contact-us/
http://localhost:3000/about-esv/faqs/esvconnect-licensing/#collapse-37-title
http://localhost:3000/licensing-coes/licence-training-assessments/cpd/

Below URLs without trailing slash is working:
http://localhost:3000/about-esv/contact-us
http://localhost:3000/about-esv/faqs/esvconnect-licensing#collapse-37-title
http://localhost:3000/licensing-coes/licence-training-assessments/cpd

### Describe the bug

The endpoint `/api/tide/page` at @dpc-sdp/nuxt-ripple/server/api/tide/page.ts, is currently taking the route as is.

However Drupal endpoint will return 404 if the path is a redirect
https://content.esv.vic.gov.au/api/v1/route?site=13&path=/about-esv/contact-us/ => return 404
https://content.esv.vic.gov.au/api/v1/route?site=13&path=/about-esv/contact-us => return details

I have raised a quick PR to resolve it since it is affecting prod issue,
https://github.com/dpc-sdp/esv-vic-gov-au/pull/93

The solution is to remove the trailing slash
```
    const path = query.path !== '/' ? query.path.replace(/\/$/, '') : query.path
    const pageResponse = await tidePageApi.getPageByPath(
      path,
      query.site,
      {},
      headers,
      sectionId
    )
```

Let me know if this is a correct solution, and I am happy to raise a PR if needed.

### Final checks

- [X] Read the [contribution guide](https://ripple.sdp.vic.gov.au/design-system/about/contributing).
- [X] Check existing [discussions](https://github.com/dpc-sdp/ripple-framework/discussions) and [issues](https://github.com/dpc-sdp/ripple-framework/issues).

**Comment by waitingallday** [comment]
@awset Thanks for this, we had a similar solution in Ripple 1 but were expecting it to be resolved at the back end this time (it hasn't been resolved). Would be happy to accept a PR for this, the solution you've suggested looks fine.

**Comment by awset** [comment]
hi @waitingallday I have no permission to push my changes, so I attached below the patch file.
[remove-trailing-slash.patch](https://github.com/user-attachments/files/15764429/remove-trailing-slash.patch)
