### ISSUE TITLE
Allow passing accordion title/content via slots

### ISSUE THREAD

**Issue by bgilhome-now** [dpc-sdp/ripple-framework#1288]
### Describe the feature

To be able to easily render a component (e.g. a `RplDataTable`) within a `RplAccordion` item, by using a slot for accordion content.

### Motivation

Currently the accordion takes an `items` array of objects to define item id, title & content (HTML passed as string). This makes it difficult to setup complex HTML or render Vue components in accordion content.

### Proposal

Use a slot (default slot) to capture accordion content. The slot content's children will be used as the content for the separate `items` entries. i.e. slot children length must equal `items` length.

Titles could optionally be passed the same way, via a named slot `title`. The `items` prop could even be optional, using an auto-assigned integer index (1-based) as `item.id` if not set.

### Benefits

Ease of rendering accordions with complex content.

### Drawbacks

Maybe confusion as to the slot children aspect (i.e. slot has 5 tags => 5 accordion items)? Might dynamically named slots e.g. `<slot name="content[0]">` be better, or more confusing?

### Adoption strategy

Update documentation. No breaking changes, accordion can be used as current.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be created outside of Ripple-framework as a layer?

### Final checks

- [X] I have read the [contribution guide](https://ripple.sdp.vic.gov.au/design-system/about/contributing) for information on submitting a feature request.
- [X] I have checked the [discussions](https://github.com/dpc-sdp/ripple-framework/discussions) and [issues](https://github.com/dpc-sdp/ripple-framework/issues) for duplicate feature requests.

**Comment by bgilhome-now** [comment]
PR at the above issue.

**Comment by dylankelly** [comment]
Agree with this entirely @bgilhome-now - It was missed when it was originally implemented. I'll see what we can do to get this in the backlog

**Comment by bgilhome-now** [comment]
Thanks @dylankelly !

**Comment by lambry** [comment]
Closing issue as this has been implemented here: https://github.com/dpc-sdp/ripple-framework/pull/1327
