### ISSUE TITLE
Map: add clustering distance prop

### ISSUE THREAD

**Issue by bgilhome-now** [dpc-sdp/ripple-framework#1290]
### Describe the feature

Depending on the number/spread of markers in a map, it might be useful/desired to set the clustering distance, or even disable clustering. Adding `clusteringDistance` as an optional prop to `RplMap` (with default as current at 100) could achieve this.

### Motivation

In the current EPA project, the custom map uses RplMap to render the map & markers. However, there are instances where the client would like to disable clustering.

### Proposal

Add `clusteringDistance` as an optional prop to `RplMap` and pass to the `ol-animated-clusterlayer` component in the template. PR will be created for this.

### Benefits

More control over clustering.

### Drawbacks

Possibility of developers setting non-sensible clustering distance values.

### Adoption strategy

Update documentation - on breaking changes.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be created outside of Ripple-framework as a layer?

### Final checks

- [X] I have read the [contribution guide](https://ripple.sdp.vic.gov.au/design-system/about/contributing) for information on submitting a feature request.
- [X] I have checked the [discussions](https://github.com/dpc-sdp/ripple-framework/discussions) and [issues](https://github.com/dpc-sdp/ripple-framework/issues) for duplicate feature requests.

**Comment by bgilhome-now** [comment]
PR above.

**Comment by dylankelly** [comment]
thanks @bgilhome-now - PR looks good, its low risk so I'm happy to get it into next release [2.14.0](https://github.com/dpc-sdp/ripple-framework/milestone/17).

**Comment by bgilhome-now** [comment]
Great, thanks all!

**Comment by dylankelly** [comment]
This was implemented in https://github.com/dpc-sdp/ripple-framework/releases/tag/2.14.0
