### ISSUE TITLE
[BUG] Related links contain `internal:` URI prefix

### ISSUE THREAD

**Issue by bgilhome-now** [dpc-sdp/ripple-framework#1321]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.2`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `features`, `modules`, `i18n`, `css`, `postcss`, `vite`, `components`, `routeRules`, `extends`
- Runtime Modules:  `@nuxtjs/i18n@8.3.1`
- Build Modules:    `-`

### Reproduction

Edit a Landing Page in Tide and add a related link with an internal URI (e.g. using a path alias `internal:/about-us`). Save & publish the changes and view the page on the frontend - the related link will have a URL of `internal:/about-us`.

### Describe the bug

When passing related link data from Tide to Ripple, `internal:` scheme URIs are passed through without handling/removing the scheme.

### Final checks

- [X] Read the [contribution guide](https://ripple.sdp.vic.gov.au/design-system/about/contributing).
- [X] Check existing [discussions](https://github.com/dpc-sdp/ripple-framework/discussions) and [issues](https://github.com/dpc-sdp/ripple-framework/issues).

**Comment by lambry** [comment]
Fix by: https://github.com/dpc-sdp/ripple-framework/pull/1334
